package com.rdpairs.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "player")
public class DeltenPlayer {

	// An autogenerated id (unique for each player in the db)

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id_player;
	
	@NotNull
	private String name;
	
	@NotNull
	private String email;
	
	
	// Public methods

	public DeltenPlayer() {
	}

	public DeltenPlayer(int id_player) {
		this.id_player = id_player;
	}

	public DeltenPlayer(String name, String email) {
		this.name = name;
		this.email = email;
	}

	// Getter and setter methods

	public long getIdPlayer() {
		return id_player;
	}

	public void setIdPlayer(int id_player) {
		this.id_player = id_player;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}